### ISSUE TITLE
spatialmath import error 

### ISSUE THREAD

**Issue by mostafanorouzi** [bdaiinstitute/spatialmath-python#80]
i got this error when run on jetson nano python 3.6 :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sadid/pyenv/sadidrobot/lib/python3.6/site-packages/spatialmath/__init__.py", line 1, in <module>
    from spatialmath.pose2d import SO2, SE2
  File "/home/sadid/pyenv/sadidrobot/lib/python3.6/site-packages/spatialmath/pose2d.py", line 26, in <module>
    from spatialmath.base import argcheck
  File "/home/sadid/pyenv/sadidrobot/lib/python3.6/site-packages/spatialmath/base/__init__.py", line 7, in <module>
    from spatialmath.base.transforms2d import *  # lgtm [py/polluting-import]
  File "/home/sadid/pyenv/sadidrobot/lib/python3.6/site-packages/spatialmath/base/transforms2d.py", line 20, in <module>
    import spatialmath.base as smb
AttributeError: module 'spatialmath' has no attribute 'base'
>>> from spatialmath import base as base
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sadid/pyenv/sadidrobot/lib/python3.6/site-packages/spatialmath/__init__.py", line 1, in <module>
    from spatialmath.pose2d import SO2, SE2
  File "/home/sadid/pyenv/sadidrobot/lib/python3.6/site-packages/spatialmath/pose2d.py", line 26, in <module>
    from spatialmath.base import argcheck
  File "/home/sadid/pyenv/sadidrobot/lib/python3.6/site-packages/spatialmath/base/__init__.py", line 7, in <module>
    from spatialmath.base.transforms2d import *  # lgtm [py/polluting-import]
  File "/home/sadid/pyenv/sadidrobot/lib/python3.6/site-packages/spatialmath/base/transforms2d.py", line 20, in <module>
    import spatialmath.base as smb
AttributeError: module 'spatialmath' has no attribute 'base'

**Comment by petercorke** [comment]
We're not supporting Python 3.6, 3.7 is the oldest.  I can replicate your problem with Python 3.6 on a Mac.  There have been changes with the semantics of import statements over time, but there are also other modern Python features that are used throughout the toolbox.  Any chance you can upgrade?
